title: [BurnSoft.Net]
description: [Open Source Applications for the world to play with!]

theme: leapday

readme_index:
  with_frontmatter: true

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: True


  
  
